# Generated by Django 3.0.3 on 2020-02-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clack_app', '0002_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_level',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
